apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wth90iehn-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wth90iehn-go 
  name: wth90iehn-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wth90iehn-go 
